services:
  volume-instantiation:
    # Ref: https://github.com/moby/moby/issues/47842#issuecomment-2249050939
    image: ubuntu:22.04
    container_name: ros2-volume-instantiation
    command: bash -c "
        mkdir -p /isaac-sim/cache/{kit,ov,pip,glcache,computecache} &&
        mkdir -p /isaac-sim/{logs,data,documents} &&
        mkdir -p /isaac-sim/standalone/cache/ov &&
        mkdir -p /isaac-sim/standalone/{logs,data} &&
        chown -R 1000:1000 /isaac-sim"
    volumes:
      - isaac-sim-cache:/isaac-sim
  aloha-ws:
    depends_on:
      - volume-instantiation
    build:
      context: .
      dockerfile: Dockerfile
      # TODO: Specify the target platform to build the image, otherwise it will build for the host platform.
      # Reference: https://docs.docker.com/compose/compose-file/build/#platforms
      # platforms:
      #   - "linux/arm64"
      cache_from:
        - j3soon/ros2-aloha-ws:buildcache-amd64
        - j3soon/ros2-aloha-ws:buildcache-arm64
    image: j3soon/ros2-aloha-ws
    container_name: ros2-aloha-ws
    stdin_open: true
    tty: true
    # TODO: Comment the line below if the workspace don't need to communicate through `/dev/*` devices.
    privileged: true
    command: /bin/bash
    network_mode: host
    working_dir: /home/ros2-essentials/aloha_ws
    environment:
      # Set X11 server environment variable for existing display.
      - DISPLAY=$DISPLAY
      # References:
      # - https://docs.ros.org/en/humble/Concepts/Intermediate/About-Domain-ID.html
      # - https://docs.ros.org/en/humble/Tutorials/Beginner-CLI-Tools/Configuring-ROS2-Environment.html
      # - https://docs.ros.org/en/humble/Tutorials/Demos/Logging-and-logger-configuration.html#console-output-colorizing
      - ROS_LOCALHOST_ONLY=0
        # Localhost only is disabled by default to allow communication with external devices.
      - ROS_DOMAIN_ID=0
        # Domain ID is set to 0 to allow communication through ros1_bridge.
      - RCUTILS_COLORIZED_OUTPUT=1
      - ROS2_WS=/home/ros2-essentials/aloha_ws
      # TODO: Add more environment variables here.
    # Enable GPU support.
    # Reference: https://docs.docker.com/compose/gpu-support/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    # Enable NVIDIA runtime (recommended but optional).
    # Reference: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/sample-workload.html
    runtime: nvidia
    volumes:
      # Mount local timezone into container.
      # Reference: https://stackoverflow.com/questions/57607381/how-do-i-change-timezone-in-a-docker-container
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      # Mount X11 server
      - /tmp/.X11-unix:/tmp/.X11-unix
        # X11-unix is mounted to allow GUI applications to display on host.
      - $HOME/.Xauthority:/home/user/.Xauthority
        # Xauthority is mounted to allow X11 forwarding for remote display.
      # Mount Direct Rendering Infrastructure (DRI) for hardware acceleration support such as OpenGL.
      - /dev/dri:/dev/dri
      # Mount sound card to prevent Gazebo warning.
      - /dev/snd:/dev/snd
      # Mount shared memory for ROS2 communication.
      - /dev/shm:/dev/shm
      # TODO: Uncomment the line below and comment out the three entries above to enable USB support.
      # - /dev:/dev
      # Mount Gazebo models directory to reuse models downloaded during first launch.
      # Reference: https://answers.ros.org/question/365658
      # Note that this volume is shared among all workspaces.
      - gazebo-cache:/home/user/.gazebo
      # Mount Isaac Sim cache directories.
      # Reference: https://docs.omniverse.nvidia.com/isaacsim/latest/installation/install_container.html#container-deployment
      # Note that this volume is shared among all workspaces.
      - type: volume
        source: isaac-sim-cache
        target: /isaac-sim/kit/cache
        volume:
          subpath: cache/kit
      - type: volume
        source: isaac-sim-cache
        target: /home/user/.cache/ov
        volume:
          subpath: cache/ov
      - type: volume
        source: isaac-sim-cache
        target: /home/user/.local/lib/python3.10/site-packages/omni/cache  # For Isaac Sim standalone
        volume:
          subpath: standalone/cache/ov
      - type: volume
        source: isaac-sim-cache
        target: /home/user/.cache/pip
        volume:
          subpath: cache/pip
      - type: volume
        source: isaac-sim-cache
        target: /home/user/.cache/nvidia/GLCache
        volume:
          subpath: cache/glcache
      - type: volume
        source: isaac-sim-cache
        target: /home/user/.nv/ComputeCache
        volume:
          subpath: cache/computecache
      - type: volume
        source: isaac-sim-cache
        target: /home/user/.nvidia-omniverse/logs
        volume:
          subpath: logs
      - type: volume
        source: isaac-sim-cache
        target: /home/user/.local/lib/python3.10/site-packages/omni/logs  # For Isaac Sim standalone
        volume:
          subpath: standalone/logs
      - type: volume
        source: isaac-sim-cache
        target: /home/user/.local/share/ov/data
        volume:
          subpath: data
      - type: volume
        source: isaac-sim-cache
        target: /home/user/.local/lib/python3.10/site-packages/omni/data  # For Isaac Sim standalone
        volume:
          subpath: standalone/data
      - type: volume
        source: isaac-sim-cache
        target: /home/user/Documents
        volume:
          subpath: documents
      # TODO: Add more volume mounts here.
      # Mount root workspace to allow easy access to all workspaces.
      - ../..:/home/ros2-essentials
volumes:
  gazebo-cache:
    name: ros2-gazebo-cache
  isaac-sim-cache:
    name: ros2-isaac-sim-cache
